version: "3.8"
services:
  customer-db:
    image: postgres:13.4
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: customerServiceDB
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  customer-test-db:
    profiles: ["test"]
    image: postgres:13.4
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: customerTestServiceDB
  elasticsearch-test:
    profiles: ["test"]
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"
networks:
  monitoring:
